### ISSUE TITLE
requests

### ISSUE THREAD

**Issue by Alejandro061076** [AFcPPe/EuroScope-Sector-Maker#1]
Good evening, first of all I want to tell you that I am not a developer but I am in an educational project using x plane11 and euroscope and I think this is what I have been looking for a long time, I have no idea how it works but I wanted to ask you if you can convert me a navdata to a Euroscope Sector files. From already thank you very much

**Comment by AFcPPe** [comment]
Hi there,

Thank you for reaching out. It's great to hear that you're working on an educational project involving X Plane 11 and Euroscope. I can provide you with some guidance on converting navdata to Euroscope sector files.

To begin, make sure you place the X Plane 11 navdata in the "nav" folder. This means that the "CIFP" folder should be a subdirectory of the "nav" folder. Next, run the "dataConverter.py" script located at the same level as the "nav" folder. After a few minutes, you should see several JSON files generated. These files contain the preliminary processed navdata.

To continue, run the "read()" function in the "newGen.py" script. The first parameter of the function should be the country code—for example, "ZG" for Guangzhou or "ZS" for Shanghai. The second parameter should be the path to store the files, such as "src/ZB/ZBPE". The program will output the files to "src/ZB/ZBPE.sct".

I hope this explanation helps! If you have any further questions, feel free to ask. Good luck with your project!

Best regards.

**Comment by Alejandro061076** [comment]
thank you very much my friend. I really don't understand anything about python but I will pass on your message to a guy who will surely be able to create it for me. What I am needing is that an airport plane be created in .SCT format so that when running a simulator session in euroscope the aircrafts operate correctly without going to the grass, when this is shown in x plane 11. Your scrips are you able to help me with this?

**Comment by AFcPPe** [comment]
I apologize for any confusion. The scripts I mentioned earlier are primarily designed for processing high-level route data. If you're looking to handle airport scenery elements such as taxiways, terminals, and grass areas, you may need to explore alternative methods.

One approach you can consider is reading the X-Plane 11 scenery data using a similar method and generating the desired airport data in the .SCT format. You can refer to the sector files publicly available on the VATSIM Hong Kong Division's GitHub repository as a reference for the data format.

Please note that this may require additional development work and expertise in handling X-Plane 11 scenery data. It's advisable to consult with someone experienced in X-Plane 11 development or look for existing tools or resources specifically designed for creating airport plane files in the .SCT format for Euroscope.

If you have further questions or need more guidance, feel free to ask. Good luck with your project!
